export const demoLeads = [
  {
    id: "lead-fisio-001",
    companyName: "Clínica Fisio Norte",
    contactName: "Laura Martín",
    email: "laura.martin@example.com",
    phone: "+34 600 111 222",
    sectorLabel: "Clínica de fisioterapia / readaptación",
    sectorFamily: "salud",
    employeeCount: 18,
    employeeBand: "10-49",
    leadPriority: "hot",
    leadScore: 92,
    estimatedCredit: 2363,
    requestedCourseSlug: "lesiones-neurofisiologia-dolor",
    closerBrief: "Lead hot (92/100) | Clínica Fisio Norte · 18 empleados | Sector salud | Crédito estimado 2363 EUR",
    trackingParams: { utm_source: "linkedin", utm_campaign: "fundae-clinicas" },
    stage: "nuevo",
    owner: "Sin asignar",
    nextActionAt: "Hoy 12:00",
    createdAt: "2026-06-15T08:30:00.000Z",
  },
  {
    id: "lead-gym-002",
    companyName: "Box Atlántico Training",
    contactName: "Diego Santana",
    email: "direccion@example.com",
    phone: "+34 611 000 333",
    sectorLabel: "Gimnasio / centro fitness / box",
    sectorFamily: "deporte",
    employeeCount: 8,
    employeeBand: "6-9",
    leadPriority: "warm",
    leadScore: 68,
    estimatedCredit: 1400,
    requestedCourseSlug: "master-ep-completo",
    closerBrief: "Lead warm (68/100) | Box Atlántico Training · 8 empleados | Interés entrenamiento",
    trackingParams: { utm_source: "direct" },
    stage: "contactado",
    owner: "Marta",
    nextActionAt: "Mañana 10:00",
    createdAt: "2026-06-14T16:10:00.000Z",
  },
  {
    id: "lead-wellness-003",
    companyName: "Wellness Costa Resort",
    contactName: "Nuria Campos",
    email: "rrhh@example.com",
    phone: "",
    sectorLabel: "Hotel, resort, spa o wellness",
    sectorFamily: "empresa",
    employeeCount: 55,
    employeeBand: "50-249",
    leadPriority: "hot",
    leadScore: 84,
    estimatedCredit: 5775,
    requestedCourseSlug: "",
    closerBrief: "Lead hot (84/100) | Wellness Costa Resort · 55 empleados | RRHH wellness",
    trackingParams: { utm_source: "google", utm_medium: "cpc" },
    stage: "cualificado",
    owner: "Carlos",
    nextActionAt: "Hoy 16:30",
    createdAt: "2026-06-15T09:05:00.000Z",
  },
];
